### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by swmoon203** [genadyo/LivePhotoDemo#2]
Why did you use hidden method in PHLivePhoto to show live photo?

```
SEL initWithImageURLvideoURLtargetSizecontentMode = NSSelectorFromString(@"_initWithImageURL:videoURL:targetSize:contentMode:");
```

Just using api would work

```
[PHLivePhoto requestLivePhotoWithResourceFileURLs:
```

**Comment by genadyo** [comment]
Is it working?
When I tried it with the beta it didn't.

**Comment by swmoon203** [comment]
it just works fine :)

<img width="1128" alt="screenshot of xcode 2015- 11- 14- 1-05-11" src="https://cloud.githubusercontent.com/assets/581101/11150520/c4dae9f8-8a6b-11e5-9685-13121afe9631.png">

**Comment by swmoon203** [comment]
it didn't work when I put only mov file path into fileURLs parameter

**Comment by genadyo** [comment]
Pull request and I'll update!

**Comment by swmoon203** [comment]
you may need to handle errors 
Which I didn't
