### ISSUE TITLE
Live Photos have no Audio.

### ISSUE THREAD

**Issue by ProiOSDeveloper** [genadyo/LivePhotoDemo#6]
Unable to record audio in Live Photos. Tried on iPhone 6+.

**Comment by genadyo** [comment]
Feel free to send pull requests.

**Comment by Raymond26** [comment]
+1.  Is there a blocker / issue that prevents audio from being included easily?

**Comment by genadyo** [comment]
Interesting, Any updates?

**Comment by aiyub007** [comment]
SAME PROBLEM HERE.

**Comment by sanjukhunt** [comment]
Just change the write function of QuickTimeMov.swift class and audio can be added to live photo if video has audio. 
func write(_ dest : String, assetIdentifier : String) {
        
        var audioReader : AVAssetReader? = nil
        var audioWriterInput : AVAssetWriterInput? = nil
        var audioReaderOutput : AVAssetReaderOutput? = nil
        do {
            // --------------------------------------------------
            // reader for source video
            // --------------------------------------------------
            guard let track = self.track(AVMediaTypeVideo) else {
                print("not found video track")
                return
            }
            let (reader, output) = try self.reader(track,
                                                   settings: [kCVPixelBufferPixelFormatTypeKey as String:
                                                    NSNumber(value: kCVPixelFormatType_32BGRA as UInt32)])
            // --------------------------------------------------
            // writer for mov
            // --------------------------------------------------
            let writer = try AVAssetWriter(outputURL: URL(fileURLWithPath: dest), fileType: AVFileTypeQuickTimeMovie)
            writer.metadata = [metadataFor(assetIdentifier)]
            
            // video track
            let input = AVAssetWriterInput(mediaType: AVMediaTypeVideo,
                                           outputSettings: videoSettings(track.naturalSize))
            input.expectsMediaDataInRealTime = true
            input.transform = track.preferredTransform
            writer.add(input)
            
            
            let url = URL(fileURLWithPath: self.path)
            let aAudioAsset : AVAsset = AVAsset(url: url)
            
            if aAudioAsset.tracks.count > 1 {
                print("Has Audio")
                //setup audio writer
                audioWriterInput = AVAssetWriterInput(mediaType: AVMediaTypeAudio, outputSettings: nil)
                
                audioWriterInput?.expectsMediaDataInRealTime = false
                if writer.canAdd(audioWriterInput!){
                    writer.add(audioWriterInput!)
                }
                //setup audio reader
                let audioTrack:AVAssetTrack = aAudioAsset.tracks(withMediaType: AVMediaTypeAudio).first!
                audioReaderOutput = AVAssetReaderTrackOutput(track: audioTrack, outputSettings: nil)
                
                do{
                    audioReader = try AVAssetReader(asset: aAudioAsset)
                }catch{
                    fatalError("Unable to read Asset: \(error) : ")
                }
                //let audioReader:AVAssetReader = AVAssetReader(asset: aAudioAsset, error: &error)
                if (audioReader?.canAdd(audioReaderOutput!))! {
                    audioReader?.add(audioReaderOutput!)
                } else {
                    print("cant add audio reader")
                }
            }
            
            // metadata track
            let adapter = metadataAdapter()
            writer.add(adapter.assetWriterInput)
            
            // --------------------------------------------------
            // creating video
            // --------------------------------------------------
            writer.startWriting()
            reader.startReading()
            writer.startSession(atSourceTime: kCMTimeZero)
            
            // write metadata track
            adapter.append(AVTimedMetadataGroup(items: [metadataForStillImageTime()],
                                                timeRange: dummyTimeRange))
            
            // write video track
            input.requestMediaDataWhenReady(on: DispatchQueue(label: "assetVideoWriterQueue", attributes: [])) {
                while(input.isReadyForMoreMediaData) {
                    if reader.status == .reading {
                        if let buffer = output.copyNextSampleBuffer() {
                            if !input.append(buffer) {
                                print("cannot write: \(writer.error)")
                                reader.cancelReading()
                            }
                        }
                    } else {
                        input.markAsFinished()
                        if reader.status == .completed && aAudioAsset.tracks.count > 1 {
                            audioReader?.startReading()
                            writer.startSession(atSourceTime: kCMTimeZero)
                            let media_queue = DispatchQueue(label: "assetAudioWriterQueue", attributes: [])
                            audioWriterInput?.requestMediaDataWhenReady(on: media_queue) {
                                while (audioWriterInput?.isReadyForMoreMediaData)! {
                                    //print("Second loop")
                                    let sampleBuffer2:CMSampleBuffer? = audioReaderOutput?.copyNextSampleBuffer()
                                    if audioReader?.status == .reading && sampleBuffer2 != nil {
                                        if !(audioWriterInput?.append(sampleBuffer2!))! {
                                            audioReader?.cancelReading()
                                        }
                                    }else {
                                        audioWriterInput?.markAsFinished()
                                        print("Audio writer finish")
                                        writer.finishWriting() {
                                            if let e = writer.error {
                                                print("cannot write: \(e)")
                                            } else {
                                                print("finish writing.")
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        else {
                            print("Video Reader not completed")
                            writer.finishWriting() {
                                if let e = writer.error {
                                    print("cannot write: \(e)")
                                } else {
                                    print("finish writing.")
                                }
                            }
                        }
                    }
                }
            }
            while writer.status == .writing {
                RunLoop.current.run(until: Date(timeIntervalSinceNow: 0.5))
            }
            if let e = writer.error {
                print("cannot write: \(e)")
            }
        } catch {
            print("error")
        }
    }

**Comment by genadyo** [comment]
Can you submit a PR?

**Comment by sanjukhunt** [comment]
I have tried but i am getting "Unexpected HTTP status code 403(-1)" error while pushing the code to new branch.

**Comment by genadyo** [comment]
Fork it and create PR

**Comment by sanjukhunt** [comment]
Here is pull Request

https://github.com/genadyo/LivePhotoDemo/pull/14
