### ISSUE TITLE
Auto reverse in live photo.

### ISSUE THREAD

**Issue by raheelahmad786** [genadyo/LivePhotoDemo#8]
I have tried your demo, It is generating live photo fine. But problem is live photo is not doing auto reverse when we release tap (or force touch) on live photo. Can you please help me in that?

**Comment by genadyo** [comment]
Where did you see that live photos do auto reverse?

**Comment by kathampy** [comment]
The built-in live wallpapers do reverse on release. The playback speed also varies with force touch pressure. Can you check if there is some way to enable this for when you export a live photo for use as a wallpaper?

**Comment by ChokShen** [comment]
> The built-in live wallpapers do reverse on release. The playback speed also varies with force touch pressure. Can you check if there is some way to enable this for when you export a live photo for use as a wallpaper?

Did you fix it ? I have same  issue.
