### ISSUE TITLE
Broken in iOS 10

### ISSUE THREAD

**Issue by aasatt** [genadyo/LivePhotoDemo#9]
Looks like saving is broken once again in iOS 10. I know they introduced a way to capture Live Photos on capable devices, I wonder if they have a different way to save them now.

**Comment by genadyo** [comment]
Did you figure it out? I'll check it next week.

**Comment by aasatt** [comment]
Not yet.

**Comment by rscodra** [comment]
Any updates? I'm having trouble figuring this out.

**Comment by genadyo** [comment]
Going to try it soon, hold tight!

**Comment by rscodra** [comment]
Great, thanks! I'll keep you updated if i find anything.

**Comment by aasatt** [comment]
Closed because it started working again. It was only broken for one or two beta releases.

**Comment by genadyo** [comment]
Thanks!
